### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by rhysperry111** [naipotato/Replay#4]
Hi, I am looking into creating an AUR package for this. Would that be ok in it's current state of development, or would you want me to wait until it is stable?

**Comment by rhysperry111** [comment]
Is libhandy-1/gee-0.8 the same as libhandy/gee? Do they need specific versions?

**Comment by nahuelwexd** [comment]
Hi! Thanks for showing interest in my little project :) I wanted to create an AUR package when the project was finished, or at least in a version that would be useful for someone, since currently it is only an empty window hehe :sweat_smile:

If you want to create it, do it :D Just post a notice that it is currently in a very early stage of development and therefore many features may be missing (such as being able to even see a grid of videos)

> Is libhandy-1/gee-0.8 the same as libhandy/gee?

`gee-0.8` yes, it is the `libgee` found in Arch repos, but `libhandy-1` is not the one found in repos. `libhandy-1` is a version that has not yet come out, so you should use `libhandy-git`.

I'm using pkg-config names for the deps since I think that are more "distro agnostic" than package names. On Arch you can use `pacman -Fy gee-0.8.pc` in order to know which package to use

Also, you will need to take a look at [UTLib](https://github.com/nahuelwexd/UTLib) since I'm gonna use that library as the core of this project.

> Also, which deps are runtime and which deps are build?

`meson` is the build system => Build dep
`vala` is the compiler => Build dep
`sassc` is the compiler for sass files => Build dep

The rest are shared libraries, so they're runtime deps

**Comment by nahuelwexd** [comment]
If you need help with something, don't hesitate to ping me :)

**Comment by nahuelwexd** [comment]
Ah, I forgot, it is very possible that I will soon change the name of the project to one more consistent with the names used for GNOME apps, since the current one is inherited from a time when the project was intended to be a UWP app for Windows 10

If you have ideas for a name idea that fits with this [article](https://blogs.gnome.org/tbernard/2019/04/26/naming-your-app), tell me :D
